{% set version = '0.1.2' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-unigd
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/unigd_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/unigd/unigd_{{ version }}.tar.gz
  sha256: 27f3315ef93848f72653662e14d2c95d69da5c44d5424b56f64a66149d96d347

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cpp11 >=0.2.4
    - r-systemfonts >=1.0.0
    - cairo
    - libpng
    - libtiff
    - libzlib
  run:
    - r-base
    - r-cpp11 >=0.2.4
    - r-systemfonts >=1.0.0

test:
  commands:
    - $R -e "library('unigd')"           # [not win]
    - "\"%R%\" -e \"library('unigd')\""  # [win]

about:
  home: https://nx10.github.io/unigd/
  dev_url: https://github.com/nx10/unigd
  license: GPL-2.0-or-later
  summary: A unified R graphics backend. Render R graphics fast and easy to many common file
    formats. Provides a thread safe 'C' interface for asynchronous rendering of R graphics.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - {{ environ["SRC_DIR"] }}/inst/licenses/fmt-MIT.txt
    - {{ environ["SRC_DIR"] }}/inst/licenses/svglite-GPL-2.txt

extra:
  recipe-maintainers:
    - conda-forge/r
